name: AbysmalScoreboard
version: '${project.version}'
description: A plugin for tracking player deaths and pvp kills using a scoreboard
author: d3ni3dj3sus
main: net.theabyssmc.abysmalscoreboard.AbysmalScoreboard
api-version: '1.20'
commands:
  scoreboard:
    description: "This command toggles the scoreboard"
    usage: "/scoreboard"
    aliases: [sb, scoreboard]
