name: AbysmalScoreboard
version: '${project.version}'
main: net.theabyssmc.abysmalscoreboard.AbysmalScoreboard
api-version: '1.20'
load: STARTUP
commands:
  scoreboard:
    description: This command toggles the scoreboard.
